/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_orieange_liblas_LasReader */

#ifndef _Included_com_orieange_liblas_LasReader
#define _Included_com_orieange_liblas_LasReader
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_orieange_liblas_LasReader
	 * Method:    read
	 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
	 */
	JNIEXPORT jobject JNICALL Java_com_orieange_liblas_LasReader_read
	(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
